services:
  # PHP + Laravel (uses custom Dockerfile)
  php:
    image: astafa/location-app-cicd:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - sql-db
    networks:
      - location-network
    environment:
      DB_HOST: sql-db
      DB_PORT: 3306
      DB_DATABASE: docker_db
      DB_USERNAME: root
      DB_PASSWORD: astafa@1234

  # NGINX to serve Laravel
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/app
    depends_on:
      - php
    networks:
      - location-network

  # MySQL
  sql-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_ROOT_PASSWORD: astafa@1234
    volumes:
      - location-data:/var/lib/mysql
    networks:
      - location-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: sql-db
      PMA_USER: root
      PMA_PASSWORD: astafa@1234
    ports:
      - 8081:80
    networks:
      - location-network

networks:
  location-network:

volumes:
  location-data:
