
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - sql-db
    networks:
      - location-network
    environment:
      DB_HOST: sql-db
      DB_PORT: 3306
      DB_DATABASE: docker_db
      DB_USERNAME: root
      DB_PASSWORD: astafa@1234
    command: sh -c "\
      composer install && \
      php artisan config:cache && \
      php artisan route:cache && \
      php artisan view:cache && \
      mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache && \
      chmod -R 777 storage bootstrap/cache && \
      php artisan migrate --force && \
      php-fpm"

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/app
    depends_on:
      - php
    networks:
      - location-network

  sql-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_ROOT_PASSWORD: astafa@1234
    volumes:
      - location-data:/var/lib/mysql
    networks:
      - location-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: sql-db
      PMA_USER: root
      PMA_PASSWORD: astafa@1234
    ports:
      - 8081:80
    networks:
      - location-network

networks:
  location-network:

volumes:
  location-data:
